-- Generated seed: NNI Badminton 2026 - Men's Singles
-- 212 players, draw seed 20261
begin;
delete from matches; delete from players;
insert into players (id, name, employee_id) values (1, 'Abhijay Singh', '41428');
insert into players (id, name, employee_id) values (2, 'Piyush Shukla', '51664');
insert into players (id, name, employee_id) values (3, 'Ansh Sharma', '55302');
insert into players (id, name, employee_id) values (4, 'Sethu R', '52583');
insert into players (id, name, employee_id) values (5, 'Vancha Bhaavan reddy', '44563');
insert into players (id, name, employee_id) values (6, 'Aashish Khatkar', '33223');
insert into players (id, name, employee_id) values (7, 'Piyush Aggarwal', '50326');
insert into players (id, name, employee_id) values (8, 'Vikas Gupta', '46615');
insert into players (id, name, employee_id) values (9, 'Harshil Thakkar', 'zs\ht23928');
insert into players (id, name, employee_id) values (10, 'Vishwas Baligidad', '29261');
insert into players (id, name, employee_id) values (11, 'Ritish Singh Rana', '48448');
insert into players (id, name, employee_id) values (12, 'Rahul Yadav', '26885');
insert into players (id, name, employee_id) values (13, 'Divyansh Sharma', '46871');
insert into players (id, name, employee_id) values (14, 'Atharv Deokar', '48016');
insert into players (id, name, employee_id) values (15, 'Parth Kudale', '49513');
insert into players (id, name, employee_id) values (16, 'Shazil Sihan P', '54379');
insert into players (id, name, employee_id) values (17, 'Rishu Kumar', '39337');
insert into players (id, name, employee_id) values (18, 'Jayant Matte', '41227');
insert into players (id, name, employee_id) values (19, 'Shailendra Singh', 'ss41124');
insert into players (id, name, employee_id) values (20, 'Viplav Khubchandani', '45424');
insert into players (id, name, employee_id) values (21, 'Shaikh Saad Ali', '47245');
insert into players (id, name, employee_id) values (22, 'Akshay Pandarkar', '53124');
insert into players (id, name, employee_id) values (23, 'Mayur Mandavkar', '40613');
insert into players (id, name, employee_id) values (24, 'Abhishek Raj', '56205');
insert into players (id, name, employee_id) values (25, 'Sahil Kamble', '47160');
insert into players (id, name, employee_id) values (26, 'Ayush Kumar Gupta', '40692');
insert into players (id, name, employee_id) values (27, 'Anurag Sahu', '43330');
insert into players (id, name, employee_id) values (28, 'Aman Das', '21460');
insert into players (id, name, employee_id) values (29, 'Aditya Singh', '36047');
insert into players (id, name, employee_id) values (30, 'Kumar Utsav', '20381');
insert into players (id, name, employee_id) values (31, 'Kumar Krishna', '22091');
insert into players (id, name, employee_id) values (32, 'Suresh Koragana', '42250');
insert into players (id, name, employee_id) values (33, 'Aditya Patil', '23390');
insert into players (id, name, employee_id) values (34, 'Pushkar Kallurkar', '48269');
insert into players (id, name, employee_id) values (35, 'Ayush Agarwal', '52132');
insert into players (id, name, employee_id) values (36, 'Gopesh Pathak', '48050');
insert into players (id, name, employee_id) values (37, 'Sahil Ashraf', '52161');
insert into players (id, name, employee_id) values (38, 'Ayush Jha', '52289');
insert into players (id, name, employee_id) values (39, 'Akshay Chauhan', '43666');
insert into players (id, name, employee_id) values (40, 'Sankalp Patil', '39154');
insert into players (id, name, employee_id) values (41, 'Jayam Shah', '46265');
insert into players (id, name, employee_id) values (42, 'Gourav Singh', '41123');
insert into players (id, name, employee_id) values (43, 'Harsh Shah', '38427');
insert into players (id, name, employee_id) values (44, 'Navyanth Gadipudi', '45747');
insert into players (id, name, employee_id) values (45, 'Dhruv Venu Nair', '52172');
insert into players (id, name, employee_id) values (46, 'Amar More', '18255');
insert into players (id, name, employee_id) values (47, 'Parth Shah', '40769');
insert into players (id, name, employee_id) values (48, 'Prajwal Tirkey', 'PT38420');
insert into players (id, name, employee_id) values (49, 'Manish Tiwari', '22904');
insert into players (id, name, employee_id) values (50, 'Yashya Garg', '52368');
insert into players (id, name, employee_id) values (51, 'Bhavya Majani', '49508');
insert into players (id, name, employee_id) values (52, 'Gaurav Bhadula', '41772');
insert into players (id, name, employee_id) values (53, 'Parv Sharma', '52506');
insert into players (id, name, employee_id) values (54, 'Abhay Sahu', '46024');
insert into players (id, name, employee_id) values (55, 'Harsh Pawar', '55281');
insert into players (id, name, employee_id) values (56, 'Shubham Jakhar', '46118');
insert into players (id, name, employee_id) values (57, 'Swastik Chaubey', '46646');
insert into players (id, name, employee_id) values (58, 'Manas Rawat', '48299');
insert into players (id, name, employee_id) values (59, 'Vaibhav Bhople', '50953');
insert into players (id, name, employee_id) values (60, 'Srinivas Challa', '48815');
insert into players (id, name, employee_id) values (61, 'Sarthak Vijayvergiya', '41350');
insert into players (id, name, employee_id) values (62, 'Pushya Mitra Kollipara', '27713');
insert into players (id, name, employee_id) values (63, 'Aashish R', '30331');
insert into players (id, name, employee_id) values (64, 'Yaswanth Naidu', '49959');
insert into players (id, name, employee_id) values (65, 'Sumit Pawar', '55517');
insert into players (id, name, employee_id) values (66, 'Dhanraj Shelke', '48688');
insert into players (id, name, employee_id) values (67, 'Ujjawal Tripathi', '52280');
insert into players (id, name, employee_id) values (68, 'Sreyash Ranjan', '49051');
insert into players (id, name, employee_id) values (69, 'Dhinesh Kumar Lakshminarayanan', '27764');
insert into players (id, name, employee_id) values (70, 'Md Huzaifa Imtiyaz', '46019');
insert into players (id, name, employee_id) values (71, 'Prarabdha Chatterjee', '54126');
insert into players (id, name, employee_id) values (72, 'Siddhivinayak Sahoo', '40750');
insert into players (id, name, employee_id) values (73, 'Amogh Choudhary', '46052');
insert into players (id, name, employee_id) values (74, 'Jyotiraditya Parihar', '55976');
insert into players (id, name, employee_id) values (75, 'Palash Batra', '48047');
insert into players (id, name, employee_id) values (76, 'Siddharth Pandey', '48675');
insert into players (id, name, employee_id) values (77, 'Abhijeet Shinde', '50160');
insert into players (id, name, employee_id) values (78, 'Melvin Saji Thomas', '41590');
insert into players (id, name, employee_id) values (79, 'Vinit Upadhyay', '40730');
insert into players (id, name, employee_id) values (80, 'Arya Nandavadekar', '52185');
insert into players (id, name, employee_id) values (81, 'Rahul Bhatt', '41168');
insert into players (id, name, employee_id) values (82, 'Aditya Kumar', '56125');
insert into players (id, name, employee_id) values (83, 'Namit Chawda', '48637');
insert into players (id, name, employee_id) values (84, 'Aryan Pandey', '41171');
insert into players (id, name, employee_id) values (85, 'Aditya Anand', '41505');
insert into players (id, name, employee_id) values (86, 'Dharavath Rahul Nayak', '52157');
insert into players (id, name, employee_id) values (87, 'Devang Harsora', '55891');
insert into players (id, name, employee_id) values (88, 'Amogh Dwivedi', '55929');
insert into players (id, name, employee_id) values (89, 'Raunak Soman', '55103');
insert into players (id, name, employee_id) values (90, 'Parth Patel', '34926');
insert into players (id, name, employee_id) values (91, 'Aryan Uppal', '50344');
insert into players (id, name, employee_id) values (92, 'Anubhav Bansal', '35272');
insert into players (id, name, employee_id) values (93, 'Varad Gattani', '42403');
insert into players (id, name, employee_id) values (94, 'Aryan Kushwaha', '47288');
insert into players (id, name, employee_id) values (95, 'Sarthak Atal', '45375');
insert into players (id, name, employee_id) values (96, 'Uday Kiran', '41162');
insert into players (id, name, employee_id) values (97, 'Asaad Khan', '41175');
insert into players (id, name, employee_id) values (98, 'Manoj Kulkarni', '17447');
insert into players (id, name, employee_id) values (99, 'Shardul Chawhan', '54011');
insert into players (id, name, employee_id) values (100, 'Korutla Sai Krishna', '43856');
insert into players (id, name, employee_id) values (101, 'Aneesh Sayal', '46358');
insert into players (id, name, employee_id) values (102, 'Ayush Attawar', '41342');
insert into players (id, name, employee_id) values (103, 'Abhishek Shukla', '52490');
insert into players (id, name, employee_id) values (104, 'Hardik Agrawal', '54634');
insert into players (id, name, employee_id) values (105, 'Varun Iyengar', '41959');
insert into players (id, name, employee_id) values (106, 'Pradeep Patel', '49005');
insert into players (id, name, employee_id) values (107, 'Yash Maheshwari', '39862');
insert into players (id, name, employee_id) values (108, 'Arnav Kundalia', '44102');
insert into players (id, name, employee_id) values (109, 'Akshar Bhatnagar', '47728');
insert into players (id, name, employee_id) values (110, 'Krupananda Mt', '28920');
insert into players (id, name, employee_id) values (111, 'Krushna Wath', '38361');
insert into players (id, name, employee_id) values (112, 'Jigar Bhanushali', '42983');
insert into players (id, name, employee_id) values (113, 'Satvik Raina', '45796');
insert into players (id, name, employee_id) values (114, 'Mahanth Ranganath', '35466');
insert into players (id, name, employee_id) values (115, 'Archit Gupta', '46073');
insert into players (id, name, employee_id) values (116, 'Rohan Newaskar', '34429');
insert into players (id, name, employee_id) values (117, 'Utkarsh Shrivastav', '46613');
insert into players (id, name, employee_id) values (118, 'Mahendra Choudhary', '48566');
insert into players (id, name, employee_id) values (119, 'Vineet Mota', '49529');
insert into players (id, name, employee_id) values (120, 'Sandeep Mishra', '43414');
insert into players (id, name, employee_id) values (121, 'Kaustubh Dusad', '21855');
insert into players (id, name, employee_id) values (122, 'Rohit Phatak', '51547');
insert into players (id, name, employee_id) values (123, 'Shubhanshu Kumar', 'Shubhanshu Kumar');
insert into players (id, name, employee_id) values (124, 'Soham Patil', '26045');
insert into players (id, name, employee_id) values (125, 'Ashish Tiwari', '46309');
insert into players (id, name, employee_id) values (126, 'Amit Sahu', '46035');
insert into players (id, name, employee_id) values (127, 'Abhinav Padoley', '19221');
insert into players (id, name, employee_id) values (128, 'Aman Kumar', '55982');
insert into players (id, name, employee_id) values (129, 'Gangadi Sai Prakash Reddy', '31084');
insert into players (id, name, employee_id) values (130, 'Nesar Joshi', '44083');
insert into players (id, name, employee_id) values (131, 'Soham Amit Panse', 'sp51546');
insert into players (id, name, employee_id) values (132, 'Pranjal Nikhare', '46323');
insert into players (id, name, employee_id) values (133, 'Rohan Patil', '51448');
insert into players (id, name, employee_id) values (134, 'Aman Mahato', '49987');
insert into players (id, name, employee_id) values (135, 'Ankit Patne', '48622');
insert into players (id, name, employee_id) values (136, 'Shubham Raj', '23524');
insert into players (id, name, employee_id) values (137, 'Ashish Gupta', '54781');
insert into players (id, name, employee_id) values (138, 'Priansh Waghela', '42142');
insert into players (id, name, employee_id) values (139, 'Shivashis Kar', '45735');
insert into players (id, name, employee_id) values (140, 'Ansh Tandon', '53756');
insert into players (id, name, employee_id) values (141, 'Harsh Nawandar', '29970');
insert into players (id, name, employee_id) values (142, 'Rohit Raina', '40596');
insert into players (id, name, employee_id) values (143, 'E Chandrahasa Reddy', '46295');
insert into players (id, name, employee_id) values (144, 'Prasanna Bhilegaonkar', '46153');
insert into players (id, name, employee_id) values (145, 'Akshat Mishra', '56924');
insert into players (id, name, employee_id) values (146, 'Hitesh Kalhane', '53810');
insert into players (id, name, employee_id) values (147, 'Piyush Dhumal', '53985');
insert into players (id, name, employee_id) values (148, 'Devansh S Raju', '49004');
insert into players (id, name, employee_id) values (149, 'Vishwas Anil Kumar', '34939');
insert into players (id, name, employee_id) values (150, 'Jitin Goyal', '38928');
insert into players (id, name, employee_id) values (151, 'Shikha Mishra', '53305');
insert into players (id, name, employee_id) values (152, 'Adeeb Khan', '51259');
insert into players (id, name, employee_id) values (153, 'Saswata Mondal', '30790');
insert into players (id, name, employee_id) values (154, 'Anirudh Kanodia', '50045');
insert into players (id, name, employee_id) values (155, 'Harsh Pande', '49030');
insert into players (id, name, employee_id) values (156, 'Suyog Kumawat', '50376');
insert into players (id, name, employee_id) values (157, 'Ashray Gautam', '42489');
insert into players (id, name, employee_id) values (158, 'Vishal Girawale', '49070');
insert into players (id, name, employee_id) values (159, 'Vasudev Dhakad', '47767');
insert into players (id, name, employee_id) values (160, 'Priyanshu Savla', '49107');
insert into players (id, name, employee_id) values (161, 'Ishan Oze', '43777');
insert into players (id, name, employee_id) values (162, 'Pratik Jadhav', '41334');
insert into players (id, name, employee_id) values (163, 'Chinmay Patke', '36902');
insert into players (id, name, employee_id) values (164, 'Kumar Aryan', '50688');
insert into players (id, name, employee_id) values (165, 'Ankit Pal', 'zs\ap48695');
insert into players (id, name, employee_id) values (166, 'Yash Vijay', '20553');
insert into players (id, name, employee_id) values (167, 'Atharva Mandhare', '56229');
insert into players (id, name, employee_id) values (168, 'Fahim Jabade', '29148');
insert into players (id, name, employee_id) values (169, 'Ayush Gajbhiye', '41258');
insert into players (id, name, employee_id) values (170, 'Mohit Kumar', '40171');
insert into players (id, name, employee_id) values (171, 'Rahul Manhas', '43539');
insert into players (id, name, employee_id) values (172, 'Ashish Yadav', '41393');
insert into players (id, name, employee_id) values (173, 'Arindam Dey', 'ad41198');
insert into players (id, name, employee_id) values (174, 'Vishal Patsariya', '52954');
insert into players (id, name, employee_id) values (175, 'Jeet Dave', '50269');
insert into players (id, name, employee_id) values (176, 'Rushikesh Jagadale', '32683');
insert into players (id, name, employee_id) values (177, 'Aniket Kadu', '37965');
insert into players (id, name, employee_id) values (178, 'Nayan Jain', '55344');
insert into players (id, name, employee_id) values (179, 'Kris Mandanka', '48278');
insert into players (id, name, employee_id) values (180, 'Sattwik Mondal', '45639');
insert into players (id, name, employee_id) values (181, 'Jitendra Patil', '45691');
insert into players (id, name, employee_id) values (182, 'Sudeep Chella', '48296');
insert into players (id, name, employee_id) values (183, 'Rishabh Ferwani', '47320');
insert into players (id, name, employee_id) values (184, 'Anirudha Kulkarni', '41257');
insert into players (id, name, employee_id) values (185, 'Aditya Shukla', '38724');
insert into players (id, name, employee_id) values (186, 'Abdulla Mohammed', '45744');
insert into players (id, name, employee_id) values (187, 'Harsh Bangar', '50715');
insert into players (id, name, employee_id) values (188, 'Pranjal Kaushal', '27089');
insert into players (id, name, employee_id) values (189, 'Vasu Sharma', '35733');
insert into players (id, name, employee_id) values (190, 'Ayaz Muzammil Hussain', '52200');
insert into players (id, name, employee_id) values (191, 'Hitesh Nayak', '22610');
insert into players (id, name, employee_id) values (192, 'Yash Kamboj', '44180');
insert into players (id, name, employee_id) values (193, 'Omkar Kargar', '34984');
insert into players (id, name, employee_id) values (194, 'Akash Deep', '43295');
insert into players (id, name, employee_id) values (195, 'Vibhav Tripathi', '45208');
insert into players (id, name, employee_id) values (196, 'Kartik Rai', '49780');
insert into players (id, name, employee_id) values (197, 'Pravi Jain', '50314');
insert into players (id, name, employee_id) values (198, 'Atharva Martiwar', '42184');
insert into players (id, name, employee_id) values (199, 'Shikhar Agrawal', '42381');
insert into players (id, name, employee_id) values (200, 'Shubham Pandey', '18150');
insert into players (id, name, employee_id) values (201, 'Raj Pandey', '36053');
insert into players (id, name, employee_id) values (202, 'Amol Dhane', '38077');
insert into players (id, name, employee_id) values (203, 'Sarthak Gupta', '54819');
insert into players (id, name, employee_id) values (204, 'Rahul Kumar Singh', '47562');
insert into players (id, name, employee_id) values (205, 'Apurva Singh', '48782');
insert into players (id, name, employee_id) values (206, 'Manas Agrawal', '49198');
insert into players (id, name, employee_id) values (207, 'Nishant Thottarath', '52393');
insert into players (id, name, employee_id) values (208, 'Sahil Luthra', '44723');
insert into players (id, name, employee_id) values (209, 'Mohit Manghnani', '35905');
insert into players (id, name, employee_id) values (210, 'Ayush Baran', '16191');
insert into players (id, name, employee_id) values (211, 'Raghav Tripathi', 'rt50406');
insert into players (id, name, employee_id) values (212, 'Sharan Sathwik K P', '42444');
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1, 'R1', 1, 0, 1, 2, false, 1000, 1, 1127, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (2, 'R1', 1, 1, 3, 4, false, 1001, 1, 1128, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (3, 'R1', 1, 2, 5, 6, false, 1001, 2, 1128, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (4, 'R1', 1, 3, 7, 8, false, 1002, 1, 1129, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (5, 'R1', 1, 4, 9, 10, false, 1002, 2, 1129, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (6, 'R1', 1, 5, 11, 12, false, 1003, 1, 1130, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (7, 'R1', 1, 6, 13, 14, false, 1004, 1, 1131, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (8, 'R1', 1, 7, 15, 16, false, 1004, 2, 1131, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (9, 'R1', 1, 8, 17, 18, false, 1005, 1, 1132, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (10, 'R1', 1, 9, 19, 20, false, 1005, 2, 1132, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (11, 'R1', 1, 10, 21, 22, false, 1006, 1, 1133, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (12, 'R1', 1, 11, 23, 24, false, 1007, 1, 1134, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (13, 'R1', 1, 12, 25, 26, false, 1007, 2, 1134, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (14, 'R1', 1, 13, 27, 28, false, 1008, 1, 1135, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (15, 'R1', 1, 14, 29, 30, false, 1008, 2, 1135, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (16, 'R1', 1, 15, 31, 32, false, 1009, 1, 1136, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (17, 'R1', 1, 16, 33, 34, false, 1010, 1, 1137, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (18, 'R1', 1, 17, 35, 36, false, 1010, 2, 1137, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (19, 'R1', 1, 18, 37, 38, false, 1011, 1, 1138, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (20, 'R1', 1, 19, 39, 40, false, 1011, 2, 1138, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (21, 'R1', 1, 20, 41, 42, false, 1012, 1, 1139, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (22, 'R1', 1, 21, 43, 44, false, 1013, 1, 1140, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (23, 'R1', 1, 22, 45, 46, false, 1013, 2, 1140, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (24, 'R1', 1, 23, 47, 48, false, 1014, 1, 1141, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (25, 'R1', 1, 24, 49, 50, false, 1014, 2, 1141, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (26, 'R1', 1, 25, 51, 52, false, 1015, 1, 1142, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (27, 'R1', 1, 26, 53, 54, false, 1016, 1, 1143, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (28, 'R1', 1, 27, 55, 56, false, 1016, 2, 1143, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (29, 'R1', 1, 28, 57, 58, false, 1017, 1, 1144, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (30, 'R1', 1, 29, 59, 60, false, 1018, 1, 1145, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (31, 'R1', 1, 30, 61, 62, false, 1018, 2, 1145, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (32, 'R1', 1, 31, 63, 64, false, 1019, 1, 1146, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (33, 'R1', 1, 32, 65, 66, false, 1019, 2, 1146, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (34, 'R1', 1, 33, 67, 68, false, 1020, 1, 1147, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (35, 'R1', 1, 34, 69, 70, false, 1021, 1, 1148, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (36, 'R1', 1, 35, 71, 72, false, 1021, 2, 1148, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (37, 'R1', 1, 36, 73, 74, false, 1022, 1, 1149, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (38, 'R1', 1, 37, 75, 76, false, 1022, 2, 1149, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (39, 'R1', 1, 38, 77, 78, false, 1023, 1, 1150, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (40, 'R1', 1, 39, 79, 80, false, 1024, 1, 1151, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (41, 'R1', 1, 40, 81, 82, false, 1024, 2, 1151, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (42, 'R1', 1, 41, 83, 84, false, 1025, 1, 1152, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (43, 'R1', 1, 42, 85, 86, false, 1025, 2, 1152, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (44, 'R1', 1, 43, 87, 88, false, 1026, 1, 1153, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (45, 'R1', 1, 44, 89, 90, false, 1027, 1, 1154, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (46, 'R1', 1, 45, 91, 92, false, 1027, 2, 1154, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (47, 'R1', 1, 46, 93, 94, false, 1028, 1, 1155, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (48, 'R1', 1, 47, 95, 96, false, 1028, 2, 1155, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (49, 'R1', 1, 48, 97, 98, false, 1029, 1, 1156, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (50, 'R1', 1, 49, 99, 100, false, 1030, 1, 1157, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (51, 'R1', 1, 50, 101, 102, false, 1030, 2, 1157, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (52, 'R1', 1, 51, 103, 104, false, 1031, 1, 1158, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (53, 'R1', 1, 52, 105, 106, false, 1031, 2, 1158, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (54, 'R1', 1, 53, 107, 108, false, 1032, 1, 1159, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (55, 'R1', 1, 54, 109, 110, false, 1033, 1, 1160, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (56, 'R1', 1, 55, 111, 112, false, 1033, 2, 1160, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (57, 'R1', 1, 56, 113, 114, false, 1034, 1, 1161, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (58, 'R1', 1, 57, 115, 116, false, 1034, 2, 1161, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (59, 'R1', 1, 58, 117, 118, false, 1035, 1, 1162, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (60, 'R1', 1, 59, 119, 120, false, 1036, 1, 1163, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (61, 'R1', 1, 60, 121, 122, false, 1036, 2, 1163, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (62, 'R1', 1, 61, 123, 124, false, 1037, 1, 1164, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (63, 'R1', 1, 62, 125, 126, false, 1037, 2, 1164, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (64, 'R1', 1, 63, 127, 128, false, 1038, 1, 1165, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (65, 'R1', 1, 64, 129, 130, false, 1039, 1, 1166, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (66, 'R1', 1, 65, 131, 132, false, 1039, 2, 1166, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (67, 'R1', 1, 66, 133, 134, false, 1040, 1, 1167, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (68, 'R1', 1, 67, 135, 136, false, 1040, 2, 1167, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (69, 'R1', 1, 68, 137, 138, false, 1041, 1, 1168, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (70, 'R1', 1, 69, 139, 140, false, 1042, 1, 1169, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (71, 'R1', 1, 70, 141, 142, false, 1042, 2, 1169, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (72, 'R1', 1, 71, 143, 144, false, 1043, 1, 1170, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (73, 'R1', 1, 72, 145, 146, false, 1043, 2, 1170, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (74, 'R1', 1, 73, 147, 148, false, 1044, 1, 1171, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (75, 'R1', 1, 74, 149, 150, false, 1045, 1, 1172, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (76, 'R1', 1, 75, 151, 152, false, 1045, 2, 1172, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (77, 'R1', 1, 76, 153, 154, false, 1046, 1, 1173, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (78, 'R1', 1, 77, 155, 156, false, 1046, 2, 1173, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (79, 'R1', 1, 78, 157, 158, false, 1047, 1, 1174, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (80, 'R1', 1, 79, 159, 160, false, 1048, 1, 1175, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (81, 'R1', 1, 80, 161, 162, false, 1048, 2, 1175, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (82, 'R1', 1, 81, 163, 164, false, 1049, 1, 1176, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (83, 'R1', 1, 82, 165, 166, false, 1050, 1, 1177, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (84, 'R1', 1, 83, 167, 168, false, 1050, 2, 1177, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (85, 'R1', 1, 84, 169, 170, false, 1051, 1, 1178, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (86, 'R1', 1, 85, 171, 172, false, 1051, 2, 1178, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (87, 'R1', 1, 86, 173, 174, false, 1052, 1, 1179, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (88, 'R1', 1, 87, 175, 176, false, 1053, 1, 1180, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (89, 'R1', 1, 88, 177, 178, false, 1053, 2, 1180, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (90, 'R1', 1, 89, 179, 180, false, 1054, 1, 1181, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (91, 'R1', 1, 90, 181, 182, false, 1054, 2, 1181, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (92, 'R1', 1, 91, 183, 184, false, 1055, 1, 1182, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (93, 'R1', 1, 92, 185, 186, false, 1056, 1, 1183, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (94, 'R1', 1, 93, 187, 188, false, 1056, 2, 1183, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (95, 'R1', 1, 94, 189, 190, false, 1057, 1, 1184, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (96, 'R1', 1, 95, 191, 192, false, 1057, 2, 1184, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (97, 'R1', 1, 96, 193, 194, false, 1058, 1, 1185, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (98, 'R1', 1, 97, 195, 196, false, 1059, 1, 1186, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (99, 'R1', 1, 98, 197, 198, false, 1059, 2, 1186, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (100, 'R1', 1, 99, 199, 200, false, 1060, 1, 1187, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (101, 'R1', 1, 100, 201, 202, false, 1060, 2, 1187, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (102, 'R1', 1, 101, 203, 204, false, 1061, 1, 1188, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (103, 'R1', 1, 102, 205, 206, false, 1062, 1, 1189, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (104, 'R1', 1, 103, 207, 208, false, 1062, 2, 1189, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (105, 'R1', 1, 104, 209, 210, false, 1063, 1, 1190, 1);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (106, 'R1', 1, 105, 211, 212, false, 1063, 2, 1190, 2);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1000, 'GOLD', 1, 0, null, null, true, 1064, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1001, 'GOLD', 1, 1, null, null, false, 1064, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1002, 'GOLD', 1, 2, null, null, false, 1065, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1003, 'GOLD', 1, 3, null, null, true, 1065, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1004, 'GOLD', 1, 4, null, null, false, 1066, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1005, 'GOLD', 1, 5, null, null, false, 1066, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1006, 'GOLD', 1, 6, null, null, true, 1067, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1007, 'GOLD', 1, 7, null, null, false, 1067, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1008, 'GOLD', 1, 8, null, null, false, 1068, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1009, 'GOLD', 1, 9, null, null, true, 1068, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1010, 'GOLD', 1, 10, null, null, false, 1069, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1011, 'GOLD', 1, 11, null, null, false, 1069, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1012, 'GOLD', 1, 12, null, null, true, 1070, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1013, 'GOLD', 1, 13, null, null, false, 1070, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1014, 'GOLD', 1, 14, null, null, false, 1071, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1015, 'GOLD', 1, 15, null, null, true, 1071, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1016, 'GOLD', 1, 16, null, null, false, 1072, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1017, 'GOLD', 1, 17, null, null, true, 1072, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1018, 'GOLD', 1, 18, null, null, false, 1073, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1019, 'GOLD', 1, 19, null, null, false, 1073, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1020, 'GOLD', 1, 20, null, null, true, 1074, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1021, 'GOLD', 1, 21, null, null, false, 1074, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1022, 'GOLD', 1, 22, null, null, false, 1075, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1023, 'GOLD', 1, 23, null, null, true, 1075, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1024, 'GOLD', 1, 24, null, null, false, 1076, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1025, 'GOLD', 1, 25, null, null, false, 1076, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1026, 'GOLD', 1, 26, null, null, true, 1077, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1027, 'GOLD', 1, 27, null, null, false, 1077, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1028, 'GOLD', 1, 28, null, null, false, 1078, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1029, 'GOLD', 1, 29, null, null, true, 1078, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1030, 'GOLD', 1, 30, null, null, false, 1079, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1031, 'GOLD', 1, 31, null, null, false, 1079, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1032, 'GOLD', 1, 32, null, null, true, 1080, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1033, 'GOLD', 1, 33, null, null, false, 1080, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1034, 'GOLD', 1, 34, null, null, false, 1081, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1035, 'GOLD', 1, 35, null, null, true, 1081, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1036, 'GOLD', 1, 36, null, null, false, 1082, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1037, 'GOLD', 1, 37, null, null, false, 1082, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1038, 'GOLD', 1, 38, null, null, true, 1083, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1039, 'GOLD', 1, 39, null, null, false, 1083, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1040, 'GOLD', 1, 40, null, null, false, 1084, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1041, 'GOLD', 1, 41, null, null, true, 1084, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1042, 'GOLD', 1, 42, null, null, false, 1085, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1043, 'GOLD', 1, 43, null, null, false, 1085, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1044, 'GOLD', 1, 44, null, null, true, 1086, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1045, 'GOLD', 1, 45, null, null, false, 1086, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1046, 'GOLD', 1, 46, null, null, false, 1087, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1047, 'GOLD', 1, 47, null, null, true, 1087, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1048, 'GOLD', 1, 48, null, null, false, 1088, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1049, 'GOLD', 1, 49, null, null, true, 1088, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1050, 'GOLD', 1, 50, null, null, false, 1089, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1051, 'GOLD', 1, 51, null, null, false, 1089, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1052, 'GOLD', 1, 52, null, null, true, 1090, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1053, 'GOLD', 1, 53, null, null, false, 1090, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1054, 'GOLD', 1, 54, null, null, false, 1091, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1055, 'GOLD', 1, 55, null, null, true, 1091, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1056, 'GOLD', 1, 56, null, null, false, 1092, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1057, 'GOLD', 1, 57, null, null, false, 1092, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1058, 'GOLD', 1, 58, null, null, true, 1093, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1059, 'GOLD', 1, 59, null, null, false, 1093, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1060, 'GOLD', 1, 60, null, null, false, 1094, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1061, 'GOLD', 1, 61, null, null, true, 1094, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1062, 'GOLD', 1, 62, null, null, false, 1095, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1063, 'GOLD', 1, 63, null, null, false, 1095, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1064, 'GOLD', 2, 0, null, null, false, 1096, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1065, 'GOLD', 2, 1, null, null, false, 1096, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1066, 'GOLD', 2, 2, null, null, false, 1097, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1067, 'GOLD', 2, 3, null, null, false, 1097, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1068, 'GOLD', 2, 4, null, null, false, 1098, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1069, 'GOLD', 2, 5, null, null, false, 1098, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1070, 'GOLD', 2, 6, null, null, false, 1099, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1071, 'GOLD', 2, 7, null, null, false, 1099, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1072, 'GOLD', 2, 8, null, null, false, 1100, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1073, 'GOLD', 2, 9, null, null, false, 1100, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1074, 'GOLD', 2, 10, null, null, false, 1101, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1075, 'GOLD', 2, 11, null, null, false, 1101, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1076, 'GOLD', 2, 12, null, null, false, 1102, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1077, 'GOLD', 2, 13, null, null, false, 1102, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1078, 'GOLD', 2, 14, null, null, false, 1103, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1079, 'GOLD', 2, 15, null, null, false, 1103, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1080, 'GOLD', 2, 16, null, null, false, 1104, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1081, 'GOLD', 2, 17, null, null, false, 1104, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1082, 'GOLD', 2, 18, null, null, false, 1105, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1083, 'GOLD', 2, 19, null, null, false, 1105, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1084, 'GOLD', 2, 20, null, null, false, 1106, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1085, 'GOLD', 2, 21, null, null, false, 1106, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1086, 'GOLD', 2, 22, null, null, false, 1107, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1087, 'GOLD', 2, 23, null, null, false, 1107, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1088, 'GOLD', 2, 24, null, null, false, 1108, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1089, 'GOLD', 2, 25, null, null, false, 1108, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1090, 'GOLD', 2, 26, null, null, false, 1109, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1091, 'GOLD', 2, 27, null, null, false, 1109, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1092, 'GOLD', 2, 28, null, null, false, 1110, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1093, 'GOLD', 2, 29, null, null, false, 1110, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1094, 'GOLD', 2, 30, null, null, false, 1111, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1095, 'GOLD', 2, 31, null, null, false, 1111, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1096, 'GOLD', 3, 0, null, null, false, 1112, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1097, 'GOLD', 3, 1, null, null, false, 1112, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1098, 'GOLD', 3, 2, null, null, false, 1113, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1099, 'GOLD', 3, 3, null, null, false, 1113, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1100, 'GOLD', 3, 4, null, null, false, 1114, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1101, 'GOLD', 3, 5, null, null, false, 1114, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1102, 'GOLD', 3, 6, null, null, false, 1115, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1103, 'GOLD', 3, 7, null, null, false, 1115, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1104, 'GOLD', 3, 8, null, null, false, 1116, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1105, 'GOLD', 3, 9, null, null, false, 1116, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1106, 'GOLD', 3, 10, null, null, false, 1117, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1107, 'GOLD', 3, 11, null, null, false, 1117, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1108, 'GOLD', 3, 12, null, null, false, 1118, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1109, 'GOLD', 3, 13, null, null, false, 1118, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1110, 'GOLD', 3, 14, null, null, false, 1119, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1111, 'GOLD', 3, 15, null, null, false, 1119, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1112, 'GOLD', 4, 0, null, null, false, 1120, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1113, 'GOLD', 4, 1, null, null, false, 1120, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1114, 'GOLD', 4, 2, null, null, false, 1121, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1115, 'GOLD', 4, 3, null, null, false, 1121, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1116, 'GOLD', 4, 4, null, null, false, 1122, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1117, 'GOLD', 4, 5, null, null, false, 1122, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1118, 'GOLD', 4, 6, null, null, false, 1123, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1119, 'GOLD', 4, 7, null, null, false, 1123, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1120, 'GOLD', 5, 0, null, null, false, 1124, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1121, 'GOLD', 5, 1, null, null, false, 1124, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1122, 'GOLD', 5, 2, null, null, false, 1125, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1123, 'GOLD', 5, 3, null, null, false, 1125, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1124, 'GOLD', 6, 0, null, null, false, 1126, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1125, 'GOLD', 6, 1, null, null, false, 1126, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1126, 'GOLD', 7, 0, null, null, false, null, null, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1127, 'SILVER', 1, 0, null, null, true, 1191, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1128, 'SILVER', 1, 1, null, null, false, 1191, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1129, 'SILVER', 1, 2, null, null, false, 1192, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1130, 'SILVER', 1, 3, null, null, true, 1192, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1131, 'SILVER', 1, 4, null, null, false, 1193, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1132, 'SILVER', 1, 5, null, null, false, 1193, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1133, 'SILVER', 1, 6, null, null, true, 1194, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1134, 'SILVER', 1, 7, null, null, false, 1194, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1135, 'SILVER', 1, 8, null, null, false, 1195, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1136, 'SILVER', 1, 9, null, null, true, 1195, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1137, 'SILVER', 1, 10, null, null, false, 1196, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1138, 'SILVER', 1, 11, null, null, false, 1196, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1139, 'SILVER', 1, 12, null, null, true, 1197, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1140, 'SILVER', 1, 13, null, null, false, 1197, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1141, 'SILVER', 1, 14, null, null, false, 1198, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1142, 'SILVER', 1, 15, null, null, true, 1198, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1143, 'SILVER', 1, 16, null, null, false, 1199, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1144, 'SILVER', 1, 17, null, null, true, 1199, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1145, 'SILVER', 1, 18, null, null, false, 1200, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1146, 'SILVER', 1, 19, null, null, false, 1200, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1147, 'SILVER', 1, 20, null, null, true, 1201, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1148, 'SILVER', 1, 21, null, null, false, 1201, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1149, 'SILVER', 1, 22, null, null, false, 1202, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1150, 'SILVER', 1, 23, null, null, true, 1202, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1151, 'SILVER', 1, 24, null, null, false, 1203, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1152, 'SILVER', 1, 25, null, null, false, 1203, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1153, 'SILVER', 1, 26, null, null, true, 1204, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1154, 'SILVER', 1, 27, null, null, false, 1204, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1155, 'SILVER', 1, 28, null, null, false, 1205, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1156, 'SILVER', 1, 29, null, null, true, 1205, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1157, 'SILVER', 1, 30, null, null, false, 1206, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1158, 'SILVER', 1, 31, null, null, false, 1206, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1159, 'SILVER', 1, 32, null, null, true, 1207, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1160, 'SILVER', 1, 33, null, null, false, 1207, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1161, 'SILVER', 1, 34, null, null, false, 1208, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1162, 'SILVER', 1, 35, null, null, true, 1208, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1163, 'SILVER', 1, 36, null, null, false, 1209, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1164, 'SILVER', 1, 37, null, null, false, 1209, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1165, 'SILVER', 1, 38, null, null, true, 1210, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1166, 'SILVER', 1, 39, null, null, false, 1210, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1167, 'SILVER', 1, 40, null, null, false, 1211, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1168, 'SILVER', 1, 41, null, null, true, 1211, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1169, 'SILVER', 1, 42, null, null, false, 1212, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1170, 'SILVER', 1, 43, null, null, false, 1212, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1171, 'SILVER', 1, 44, null, null, true, 1213, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1172, 'SILVER', 1, 45, null, null, false, 1213, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1173, 'SILVER', 1, 46, null, null, false, 1214, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1174, 'SILVER', 1, 47, null, null, true, 1214, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1175, 'SILVER', 1, 48, null, null, false, 1215, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1176, 'SILVER', 1, 49, null, null, true, 1215, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1177, 'SILVER', 1, 50, null, null, false, 1216, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1178, 'SILVER', 1, 51, null, null, false, 1216, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1179, 'SILVER', 1, 52, null, null, true, 1217, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1180, 'SILVER', 1, 53, null, null, false, 1217, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1181, 'SILVER', 1, 54, null, null, false, 1218, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1182, 'SILVER', 1, 55, null, null, true, 1218, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1183, 'SILVER', 1, 56, null, null, false, 1219, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1184, 'SILVER', 1, 57, null, null, false, 1219, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1185, 'SILVER', 1, 58, null, null, true, 1220, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1186, 'SILVER', 1, 59, null, null, false, 1220, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1187, 'SILVER', 1, 60, null, null, false, 1221, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1188, 'SILVER', 1, 61, null, null, true, 1221, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1189, 'SILVER', 1, 62, null, null, false, 1222, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1190, 'SILVER', 1, 63, null, null, false, 1222, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1191, 'SILVER', 2, 0, null, null, false, 1223, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1192, 'SILVER', 2, 1, null, null, false, 1223, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1193, 'SILVER', 2, 2, null, null, false, 1224, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1194, 'SILVER', 2, 3, null, null, false, 1224, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1195, 'SILVER', 2, 4, null, null, false, 1225, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1196, 'SILVER', 2, 5, null, null, false, 1225, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1197, 'SILVER', 2, 6, null, null, false, 1226, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1198, 'SILVER', 2, 7, null, null, false, 1226, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1199, 'SILVER', 2, 8, null, null, false, 1227, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1200, 'SILVER', 2, 9, null, null, false, 1227, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1201, 'SILVER', 2, 10, null, null, false, 1228, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1202, 'SILVER', 2, 11, null, null, false, 1228, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1203, 'SILVER', 2, 12, null, null, false, 1229, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1204, 'SILVER', 2, 13, null, null, false, 1229, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1205, 'SILVER', 2, 14, null, null, false, 1230, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1206, 'SILVER', 2, 15, null, null, false, 1230, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1207, 'SILVER', 2, 16, null, null, false, 1231, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1208, 'SILVER', 2, 17, null, null, false, 1231, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1209, 'SILVER', 2, 18, null, null, false, 1232, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1210, 'SILVER', 2, 19, null, null, false, 1232, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1211, 'SILVER', 2, 20, null, null, false, 1233, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1212, 'SILVER', 2, 21, null, null, false, 1233, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1213, 'SILVER', 2, 22, null, null, false, 1234, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1214, 'SILVER', 2, 23, null, null, false, 1234, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1215, 'SILVER', 2, 24, null, null, false, 1235, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1216, 'SILVER', 2, 25, null, null, false, 1235, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1217, 'SILVER', 2, 26, null, null, false, 1236, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1218, 'SILVER', 2, 27, null, null, false, 1236, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1219, 'SILVER', 2, 28, null, null, false, 1237, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1220, 'SILVER', 2, 29, null, null, false, 1237, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1221, 'SILVER', 2, 30, null, null, false, 1238, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1222, 'SILVER', 2, 31, null, null, false, 1238, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1223, 'SILVER', 3, 0, null, null, false, 1239, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1224, 'SILVER', 3, 1, null, null, false, 1239, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1225, 'SILVER', 3, 2, null, null, false, 1240, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1226, 'SILVER', 3, 3, null, null, false, 1240, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1227, 'SILVER', 3, 4, null, null, false, 1241, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1228, 'SILVER', 3, 5, null, null, false, 1241, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1229, 'SILVER', 3, 6, null, null, false, 1242, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1230, 'SILVER', 3, 7, null, null, false, 1242, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1231, 'SILVER', 3, 8, null, null, false, 1243, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1232, 'SILVER', 3, 9, null, null, false, 1243, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1233, 'SILVER', 3, 10, null, null, false, 1244, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1234, 'SILVER', 3, 11, null, null, false, 1244, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1235, 'SILVER', 3, 12, null, null, false, 1245, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1236, 'SILVER', 3, 13, null, null, false, 1245, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1237, 'SILVER', 3, 14, null, null, false, 1246, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1238, 'SILVER', 3, 15, null, null, false, 1246, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1239, 'SILVER', 4, 0, null, null, false, 1247, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1240, 'SILVER', 4, 1, null, null, false, 1247, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1241, 'SILVER', 4, 2, null, null, false, 1248, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1242, 'SILVER', 4, 3, null, null, false, 1248, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1243, 'SILVER', 4, 4, null, null, false, 1249, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1244, 'SILVER', 4, 5, null, null, false, 1249, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1245, 'SILVER', 4, 6, null, null, false, 1250, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1246, 'SILVER', 4, 7, null, null, false, 1250, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1247, 'SILVER', 5, 0, null, null, false, 1251, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1248, 'SILVER', 5, 1, null, null, false, 1251, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1249, 'SILVER', 5, 2, null, null, false, 1252, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1250, 'SILVER', 5, 3, null, null, false, 1252, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1251, 'SILVER', 6, 0, null, null, false, 1253, 1, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1252, 'SILVER', 6, 1, null, null, false, 1253, 2, null, null);
insert into matches (id, bracket, round, position, player1_id, player2_id, is_bye, next_match_id, next_slot, loser_next_match_id, loser_next_slot) values (1253, 'SILVER', 7, 0, null, null, false, null, null, null, null);
select setval('players_id_seq', (select max(id) from players));
select setval('matches_id_seq', (select max(id) from matches));
commit;
